"""empty message

Revision ID: b4330df7ece9
Revises: 6cf7386a1a50
Create Date: 2024-08-25 23:22:28.453741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4330df7ece9'
down_revision: Union[str, None] = '6cf7386a1a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislikes')
    op.drop_column('posts', 'likes')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'dislikes')
    op.drop_column('comments', 'likes')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
